use RustQ.Config

require_file("lib/skia/codegen/native/skia_safe.ex")
require_file("lib/skia/codegen/native/schema.ex")
require_file("lib/skia/codegen/native/enums.ex")
require_file("lib/skia/codegen/command/spec_reader.ex")
require_file("lib/skia/codegen/command/overlay/dsl.ex")
require_file("lib/skia/codegen/command/overlay.ex")
require_file("lib/skia/codegen/command/domain/shapes.ex")
require_file("lib/skia/codegen/command/domain/text.ex")
require_file("lib/skia/codegen/command/domain/images.ex")
require_file("lib/skia/codegen/command/domain/layers.ex")
require_file("lib/skia/codegen/command/domain/transforms.ex")
require_file("lib/skia/codegen/command/domain/paths.ex")
require_file("lib/skia/codegen/command/domain/clips.ex")
require_file("lib/skia/codegen/command/registry.ex")
require_file("lib/skia/codegen/rusty/support/args.ex")
require_file("lib/skia/codegen/rusty/command_domain.ex")
require_file("lib/skia/codegen/rusty/dispatch.ex")
require_file("lib/skia/codegen/rusty/support/paint_macros.ex")
require_file("lib/skia/codegen/rusty/source_sets/skia_safe.ex")
require_file("lib/skia/codegen/rusty/support/generated_callables.ex")
require_file("lib/skia/codegen/rusty/support/paint_decoders.ex")
require_file("lib/skia/codegen/rusty/support/style_helpers.ex")
require_file("lib/skia/codegen/rusty/command/clips.ex")
require_file("lib/skia/codegen/rusty/command/images.ex")
require_file("lib/skia/codegen/rusty/command/layers.ex")
require_file("lib/skia/codegen/rusty/command/paths.ex")
require_file("lib/skia/codegen/rusty/command/text.ex")
require_file("lib/skia/codegen/rusty/command/transforms.ex")
require_file("lib/skia/codegen/rusty/command/shapes.ex")
require_file("lib/skia/codegen/rust/core.ex")
require_file("lib/skia/codegen/rust/commands.ex")
require_file("lib/skia/codegen/rust/nifs.ex")
require_file("lib/skia/codegen/rust/opts.ex")
require_file("lib/skia/codegen/rust/targets.ex")

Skia.Codegen.Rust.Targets.all()
|> Enum.map(fn {name, target} ->
  generate name, Keyword.fetch!(target, :path) do
    build(Keyword.fetch!(target, :build))
  end
end)
|> List.last()
