defmodule Skia.Codegen.Enums do
  @moduledoc false

  alias RustQ.Rust
  alias Skia.Codegen.Commands
  alias Skia.Codegen.SkiaSafe

  @spec generated() :: String.t()
  def generated do
    entries =
      defs()
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} ->
        values = spec |> Keyword.fetch!(:variants) |> Enum.map(&elem(&1, 0))

        Rust.const(enum_const_name(name), {:raw, "&[&str]"}, Rust.expr(enum_values(values)),
          vis: :pub
        )
      end)

    decoders =
      defs()
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} -> enum_decoder(name, spec) end)

    "generated_enums.rs"
    |> template_path()
    |> RustQ.render_file!(
      preamble: generated_rust_preamble(),
      splice: [entries: entries, decoders: decoders]
    )
  end

  @spec atoms() :: [atom()]
  def atoms do
    defs()
    |> Enum.flat_map(fn {_name, spec} ->
      spec |> Keyword.fetch!(:variants) |> Enum.map(&elem(&1, 0))
    end)
  end

  @spec defs() :: %{atom() => keyword()}
  def defs do
    specs =
      Commands.all()
      |> Enum.flat_map(fn {_name, spec} -> Keyword.get(spec, :opts, []) end)
      |> Enum.flat_map(fn opt -> opt |> Keyword.fetch!(:type) |> enum_type_spec() end)
      |> Kernel.++(Map.to_list(Skia.Codegen.EnumSpecs.extra_specs()))

    specs
    |> Enum.uniq_by(&elem(&1, 0))
    |> Map.new(fn {name, spec} ->
      variants =
        spec
        |> Keyword.fetch!(:skia)
        |> SkiaSafe.enum_variants()

      {name, Keyword.put(spec, :variants, variants)}
    end)
  end

  defp enum_type_spec({:enum, name, opts}), do: [{name, opts}]
  defp enum_type_spec(_type), do: []

  defp enum_const_name(name) do
    rust_name = name |> Atom.to_string() |> Macro.camelize()
    "#{Macro.underscore(rust_name) |> String.upcase()}S"
  end

  defp enum_values(values) do
    values = Enum.map_join(values, ", ", &inspect(to_string(&1)))
    "&[#{values}]"
  end

  defp enum_decoder(name, spec) do
    type = Keyword.fetch!(spec, :rust)

    cases =
      spec
      |> Keyword.fetch!(:variants)
      |> Enum.map(fn {atom, variant} -> {atom, "#{Rust.type(type)}::#{variant}"} end)

    RustQ.Rustler.atom_decoder("decode_#{name}", returns: type, cases: cases)
  end

  defp template_path(name) do
    __DIR__
    |> Path.join("../../../priv/codegen/templates/#{name}")
    |> Path.expand()
  end

  defp generated_rust_preamble do
    "// Generated by mix skia.codegen. Do not edit by hand.\n\n"
  end
end
