defmodule Skia.Codegen.Enums do
  @moduledoc false

  alias RustQ.Rust
  alias Skia.Codegen.Commands
  alias Skia.Codegen.SkiaSafe

  @extra_specs %{
    encoded_image_format: [skia: "SkEncodedImageFormat", rust: :EncodedImageFormat],
    blur_style: [skia: "SkBlurStyle", rust: :BlurStyle],
    sampling: [skia: "SkFilterMode", rust: :FilterMode],
    tile_mode: [skia: "SkTileMode", rust: :TileMode],
    mipmap_mode: [skia: "SkMipmapMode", rust: :MipmapMode]
  }

  @spec generated() :: String.t()
  def generated do
    entries =
      defs()
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} ->
        values = spec |> Keyword.fetch!(:variants) |> Enum.map(&elem(&1, 0))

        Rust.const(enum_const_name(name), {:raw, "&[&str]"}, Rust.expr(enum_values(values)),
          vis: :pub
        )
      end)

    decoders =
      defs()
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} -> enum_decoder(name, spec) end)

    "generated_enums.rs"
    |> template_path()
    |> RustQ.render_file!(
      preamble: generated_rust_preamble(),
      splice: [entries: entries, decoders: decoders]
    )
  end

  @spec atoms() :: [atom()]
  def atoms do
    defs()
    |> Enum.flat_map(fn {_name, spec} ->
      spec |> Keyword.fetch!(:variants) |> Enum.map(&elem(&1, 0))
    end)
  end

  @spec defs() :: %{atom() => keyword()}
  def defs do
    specs =
      Commands.all()
      |> Enum.flat_map(fn {_name, spec} -> Keyword.get(spec, :opts, []) end)
      |> Enum.flat_map(fn opt -> opt |> Keyword.fetch!(:type) |> enum_type_spec() end)
      |> Kernel.++(Map.to_list(@extra_specs))

    specs
    |> Enum.uniq_by(&elem(&1, 0))
    |> Map.new(fn {name, spec} -> {name, resolve_spec(spec)} end)
  end

  defp enum_type_spec(%RustQ.Meta.Type{kind: :enum, meta: %{elixir_name: name} = meta}) do
    [{name, [descriptor: Map.fetch!(meta, :native_enum), rust: Map.fetch!(meta, :rust_type)]}]
  end

  defp enum_type_spec(_type), do: []

  defp resolve_spec(spec) do
    descriptor =
      Keyword.get_lazy(spec, :descriptor, fn ->
        spec |> Keyword.fetch!(:skia) |> SkiaSafe.enum_descriptor!()
      end)

    spec
    |> Keyword.put(:descriptor, descriptor)
    |> Keyword.put(:variants, RustQ.NativeEnumDescriptor.variants(descriptor))
  end

  defp enum_const_name(name) do
    rust_name = name |> Atom.to_string() |> Macro.camelize()
    "#{Macro.underscore(rust_name) |> String.upcase()}S"
  end

  defp enum_values(values) do
    values = Enum.map_join(values, ", ", &inspect(to_string(&1)))
    "&[#{values}]"
  end

  defp enum_decoder(name, spec) do
    RustQ.Rustler.atom_decoder("decode_#{name}",
      returns: Keyword.fetch!(spec, :rust),
      descriptor: Keyword.fetch!(spec, :descriptor)
    )
  end

  defp template_path(name) do
    __DIR__
    |> Path.join("../../../priv/codegen/templates/#{name}")
    |> Path.expand()
  end

  defp generated_rust_preamble do
    "// Generated by mix skia.codegen. Do not edit by hand.\n\n"
  end
end
