defmodule Skia.Codegen.Enums do
  @moduledoc false

  alias RustQ.Native.EnumDescriptor, as: NativeEnumDescriptor
  alias RustQ.Rust
  alias RustQ.Rust.AST.Builder, as: A
  alias RustQ.Rust.AST.Render
  alias RustQ.Rust.AST.TypeBuilder, as: T
  alias RustQ.Rustler
  alias Skia.Codegen.NativeSchema
  alias Skia.Codegen.SkiaSafe

  @api_enums %{
    blend_mode: "SkBlendMode",
    stroke_cap: "SkPaint_Cap",
    stroke_join: "SkPaint_Join",
    fill_rule: "SkPathFillType",
    path_op: "SkPathOp",
    clip_op: "SkClipOp",
    encoded_image_format: "SkEncodedImageFormat",
    blur_style: "SkBlurStyle",
    sampling: "SkFilterMode",
    tile_mode: "SkTileMode",
    mipmap_mode: "SkMipmapMode"
  }

  @doc false
  @spec api_enums() :: %{atom() => String.t()}
  def api_enums, do: @api_enums

  @spec generated() :: String.t()
  def generated do
    entries =
      defs()
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} ->
        values = spec |> Keyword.fetch!(:variants) |> Enum.map(&elem(&1, 0))

        Rust.const(
          enum_const_name(name),
          T.ref(T.slice(T.ref(:str))),
          Rust.expr(enum_values(values)),
          vis: :pub
        )
      end)

    decoders =
      defs()
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} -> enum_decoder(name, spec) end)

    enums_module_template()
    |> RustQ.render!(
      "generated_enums.rs",
      preamble: generated_rust_preamble(),
      splice: [entries: entries, decoders: decoders]
    )
  end

  @spec atoms() :: [atom()]
  def atoms do
    defs()
    |> Enum.flat_map(fn {_name, spec} ->
      spec |> Keyword.fetch!(:variants) |> Enum.map(&elem(&1, 0))
    end)
  end

  @spec defs() :: %{atom() => keyword()}
  def defs do
    Map.new(@api_enums, fn {name, _native_name} -> {name, spec!(name)} end)
  end

  @spec spec!(atom()) :: keyword()
  def spec!(name), do: @api_enums |> Map.fetch!(name) |> resolve_spec()

  defp resolve_spec(native_name) do
    descriptor = SkiaSafe.enum_descriptor!(native_name)

    []
    |> Keyword.put(:skia, native_name)
    |> Keyword.put(:descriptor, descriptor)
    |> Keyword.put(:rust, NativeSchema.safe_enum_type!(descriptor.name))
    |> Keyword.put(:variants, NativeEnumDescriptor.variants(descriptor))
  end

  defp enum_const_name(name) do
    rust_name = name |> Atom.to_string() |> Macro.camelize()
    "#{Macro.underscore(rust_name) |> String.upcase()}S"
  end

  defp enum_values(values) do
    values
    |> Enum.map(&to_string/1)
    |> A.slice()
    |> Render.render_expr()
  end

  defp enum_decoder(name, spec) do
    Rustler.atom_decoder("decode_#{name}",
      returns: Keyword.fetch!(spec, :rust),
      descriptor: Keyword.fetch!(spec, :descriptor)
    )
  end

  defp enums_module_template do
    """
    #![allow(dead_code)]

    use rustler::{Atom, NifResult};
    use skia_safe::{
        BlendMode, BlurStyle, ClipOp, EncodedImageFormat, FilterMode, MipmapMode, PaintCap,
        PaintJoin, PathFillType, PathOp, TileMode,
    };

    use super::atoms;

    __rq_entries!();
    __rq_decoders!();
    """
  end

  defp generated_rust_preamble do
    "// Generated by mix skia.codegen. Do not edit by hand.\n\n"
  end
end
