defmodule Skia.Codegen.Rust.Core do
  @moduledoc false

  alias RustQ.Rust
  alias Skia.Codegen.Command.Registry, as: Commands
  alias Skia.Codegen.Native.Enums, as: Enums
  alias Skia.Codegen.Rusty.Support

  @spec generated_atoms() :: String.t()
  def generated_atoms do
    atoms =
      Commands.all()
      |> Enum.flat_map(fn {name, spec} ->
        option_atoms = spec |> Keyword.get(:opts, []) |> Enum.map(&Keyword.fetch!(&1, :name))
        arg_atoms = spec |> Keyword.get(:args, []) |> Keyword.keys()
        [name, Keyword.get(spec, :op) | option_atoms ++ arg_atoms]
      end)
      |> Kernel.++(Enums.atoms())
      |> Kernel.++(rust_atom_references())
      |> Enum.reject(&is_nil/1)
      |> Enum.map(&to_string/1)
      |> Enum.uniq()
      |> Enum.sort()

    "__rq_atoms!();"
    |> RustQ.render!(
      "generated_atoms.rs",
      preamble: generated_rust_preamble(),
      splice: [atoms: RustQ.Rustler.atoms(atoms, module: false)]
    )
  end

  @spec generated_enums() :: String.t()
  def generated_enums, do: Enums.generated()

  @spec generated_dispatch() :: String.t()
  def generated_dispatch do
    cases =
      Commands.all()
      |> Enum.flat_map(fn {name, spec} ->
        case Keyword.fetch(spec, :handler) do
          {:ok, handler} -> [{Keyword.get(spec, :op, name), "#{handler}(canvas, command)"}]
          :error -> []
        end
      end)
      |> Enum.uniq()
      |> Enum.sort()

    dispatch =
      RustQ.Rustler.atom_dispatch(:draw_command,
        args: [canvas: "&skia_safe::Canvas", command: :Term],
        on: "command.map_get(atoms::op())?.decode::<Atom>()?",
        cases: cases,
        unknown: "Err(rustler::Error::BadArg)"
      )

    items = [dispatch, RustQ.Meta.AST.item(Skia.Codegen.Rusty.Dispatch, :compact_op_atom)]

    render_items(items, "generated_dispatch.rs")
  end

  @spec generated_style_helpers() :: String.t()
  def generated_style_helpers do
    Support.StyleHelpers
    |> rusty_asts()
    |> Enum.map(&render_rustq_item/1)
    |> render_items("generated_style_helpers.rs")
  end

  @spec generated_opts_helpers() :: String.t()
  def generated_opts_helpers do
    RustQ.Rustler.opts_helpers()
    |> render_items("generated_opts_helpers.rs")
  end

  @doc false
  @spec resource_specs() :: [{atom(), keyword()}]
  def resource_specs do
    [
      EncodedImage: [fields: [image: "Image"], decoder: :decode_encoded_image_ref],
      EncodedFont: [fields: [typeface: "skia_safe::Typeface"], decoder: :decode_encoded_font_ref],
      EncodedPicture: [
        fields: [bytes: "Vec<u8>", picture: "Picture"],
        decoder: :decode_encoded_picture_ref
      ],
      EncodedTextBlob: [fields: [blob: "TextBlob"], decoder: :decode_encoded_text_blob_ref],
      EncodedRuntimeEffect: [
        fields: [source: "String"],
        decoder: :decode_encoded_runtime_effect_ref
      ]
    ]
  end

  @spec generated_resources() :: String.t()
  def generated_resources do
    resources =
      resource_specs()
      |> Enum.flat_map(fn {name, opts} -> RustQ.Rustler.resource_handle(name, opts) end)

    render_items(resources, "generated_resources.rs")
  end

  def rust_atom_references do
    "native/skia_native/src/*.rs"
    |> Path.wildcard()
    |> Enum.reject(&String.ends_with?(&1, "/generated_atoms.rs"))
    |> Enum.flat_map(fn path ->
      path
      |> File.read!()
      |> RustQ.Syn.atom_references!()
    end)
  end

  def generated_rust_preamble do
    "// Generated by mix skia.codegen. Do not edit by hand.\n\n"
  end

  def render_items(items, file) do
    "__rq_items!();"
    |> RustQ.render!(file, preamble: generated_rust_preamble(), splice: [items: items])
  end

  def render_rustq_item(ast), do: Rust.ast_item(ast)

  def rusty_asts(module), do: module.__rustq_asts__()

  def rusty_ast(module, name), do: Enum.find(rusty_asts(module), &(&1.name == name))
end
