defmodule Skia.Codegen.Rust.Nifs do
  @moduledoc false

  @native_nifs [
    compile_runtime_effect: [
      args: [env: "Env<'a>", source: :String],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    render_png: [
      args: [env: "Env<'a>", batch: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    render_rgba: [
      args: [env: "Env<'a>", batch: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    render_compact_png: [
      args: [env: "Env<'a>", batch: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    render_compact_rgba: [
      args: [env: "Env<'a>", batch: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    render_jpeg: [
      args: [env: "Env<'a>", batch: "Term<'a>", quality: :u32],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    render_webp: [
      args: [env: "Env<'a>", batch: "Term<'a>", quality: :u32],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    decode_image: [
      args: [env: "Env<'a>", bytes: "Binary<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    encode_image: [
      args: [env: "Env<'a>", image_term: "Term<'a>", format: :Atom, quality: :u32],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    resize_image: [
      args: [env: "Env<'a>", image_term: "Term<'a>", width: :i32, height: :i32],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    crop_image: [
      args: [env: "Env<'a>", image_term: "Term<'a>", source: "(f64, f64, f64, f64)"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    load_font: [
      args: [env: "Env<'a>", bytes: "Binary<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    font_families: [
      args: [env: "Env<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    match_font: [
      args: [env: "Env<'a>", family: :String, weight: :i32, slant: :Atom],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    typeface_info: [
      args: [env: "Env<'a>", typeface_term: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    font_metrics: [
      args: [env: "Env<'a>", font_term: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    font_glyph_ids: [
      args: [env: "Env<'a>", font_term: "Term<'a>", text: :String],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    measure_text: [
      args: [env: "Env<'a>", text: :String, font_term: "Term<'a>", size: :f64],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    create_text_blob: [
      args: [env: "Env<'a>", text: :String, font_term: "Term<'a>", size: :f64],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    text_blob_bounds: [
      args: [env: "Env<'a>", blob_term: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    record_picture: [
      args: [env: "Env<'a>", batch: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    decode_picture: [
      args: [env: "Env<'a>", bytes: "Binary<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    encode_picture: [
      args: [env: "Env<'a>", picture_term: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    picture_info: [
      args: [env: "Env<'a>", picture_term: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ],
    path_to_svg: [
      args: [env: "Env<'a>", path_term: "Term<'a>"],
      returns: "NifResult<Term<'a>>",
      lifetime: :a
    ]
  ]

  @spec generated_native() :: String.t()
  def generated_native do
    functions =
      @native_nifs
      |> Enum.map_join("\n", fn {name, spec} ->
        args =
          spec
          |> Keyword.fetch!(:args)
          |> Keyword.keys()
          |> Enum.reject(&(&1 == :env))
          |> elixir_nif_args()

        if args == "" do
          "  def #{name}, do: :erlang.nif_error(:nif_not_loaded)"
        else
          "  def #{name}(#{args}), do: :erlang.nif_error(:nif_not_loaded)"
        end
      end)

    """
    # Generated by mix skia.codegen. Do not edit by hand.

    defmodule Skia.Native do
      @moduledoc false

      version = Mix.Project.config()[:version]

      use RustlerPrecompiled,
        otp_app: :skia,
        crate: "skia_native",
        base_url: "https://github.com/dannote/skia_ex/releases/download/v\#{version}",
        force_build: System.get_env("SKIA_EX_BUILD") in ["1", "true"],
        targets: ~w(
          aarch64-apple-darwin
          x86_64-apple-darwin
          x86_64-unknown-linux-gnu
        ),
        version: version

    #{functions}
    end
    """
  end

  @doc false
  @spec native_nif_specs() :: keyword(keyword())
  def native_nif_specs, do: @native_nifs

  @spec generated_native_nifs() :: String.t()
  def generated_native_nifs do
    wrappers =
      native_nif_specs()
      |> Enum.map(fn {name, spec} -> {name, Keyword.put(spec, :schedule, :dirty_cpu)} end)
      |> RustQ.Rustler.nif_exports()

    render_items(wrappers, "generated_nifs.rs")
  end

  defp elixir_nif_args(args), do: Enum.map_join(args, ", ", &"_#{elixir_arg_name(&1)}")

  defp elixir_arg_name(:env), do: :env
  defp elixir_arg_name(:image_term), do: :image
  defp elixir_arg_name(:font_term), do: :font
  defp elixir_arg_name(:typeface_term), do: :typeface
  defp elixir_arg_name(:picture_term), do: :picture
  defp elixir_arg_name(name), do: name

  defp render_items(items, file) do
    "__rq_items!();"
    |> RustQ.render!(file,
      preamble: "// Generated by mix skia.codegen. Do not edit by hand.\n\n",
      splice: [items: items]
    )
  end
end
