defmodule Skia.Codegen.Rust.Nifs do
  @moduledoc false

  alias RustQ.Rustler.Nif

  @source "native/skia_native/src/lib.rs"
  @native_nifs [
    :compile_runtime_effect,
    :render_png,
    :render_rgba,
    :render_compact_png,
    :render_compact_rgba,
    :render_jpeg,
    :render_webp,
    :decode_image,
    :encode_image,
    :resize_image,
    :crop_image,
    :load_font,
    :font_families,
    :match_font,
    :typeface_info,
    :font_metrics,
    :font_glyph_ids,
    :measure_text,
    :create_text_blob,
    :text_blob_bounds,
    :record_picture,
    :decode_picture,
    :encode_picture,
    :picture_info,
    :path_to_svg
  ]

  @doc false
  @spec native_nif_specs() :: [{atom(), keyword()}]
  def native_nif_specs, do: Enum.map(@native_nifs, &{&1, []})

  @spec generated_native_nifs() :: String.t()
  def generated_native_nifs do
    wrappers =
      Nif.wrappers_from_source(
        @source,
        native_nif_specs(),
        schedule: :dirty_cpu
      )

    render_items(wrappers, "generated_nifs.rs")
  end

  @spec generated_native_stubs() :: String.t()
  def generated_native_stubs do
    Nif.stubs_from_source(
      @source,
      native_nif_specs(),
      Skia.Native.GeneratedStubs
    )
  end

  defp render_items(items, file) do
    "__rq_items!();"
    |> RustQ.render!(file,
      preamble: "// Generated by mix skia.codegen. Do not edit by hand.\n\n",
      splice: [items: items]
    )
  end
end
