defmodule Skia.Codegen do
  @moduledoc false

  alias RustQ.Rust

  @spec generated_targets() :: [{atom(), keyword()}]
  def generated_targets do
    [
      generated_atoms: [
        path: "native/skia_native/src/generated_atoms.rs",
        build: &generated_atoms/0
      ],
      generated_enums: [
        path: "native/skia_native/src/generated_enums.rs",
        build: &generated_enums/0
      ],
      generated_opts: [path: "native/skia_native/src/generated_opts.rs", build: &generated_opts/0],
      command_docs: [path: "docs/commands.md", build: &generated_docs/0]
    ]
  end

  @enum_atoms %{
    sampling: [:nearest, :linear],
    stroke_cap: [:butt, :round, :square],
    stroke_join: [:miter, :round, :bevel],
    fill_rule: [:winding, :even_odd],
    blend_mode: [:src_over, :multiply, :screen, :overlay, :darken, :lighten, :clear_mode]
  }

  @enum_decoders %{
    sampling: [type: :FilterMode, variants: [nearest: :Nearest, linear: :Linear]],
    stroke_cap: [type: "paint::Cap", variants: [butt: :Butt, round: :Round, square: :Square]],
    stroke_join: [type: "paint::Join", variants: [miter: :Miter, round: :Round, bevel: :Bevel]],
    fill_rule: [type: :PathFillType, variants: [winding: :Winding, even_odd: :EvenOdd]],
    blend_mode: [
      type: :BlendMode,
      variants: [
        src_over: :SrcOver,
        multiply: :Multiply,
        screen: :Screen,
        overlay: :Overlay,
        darken: :Darken,
        lighten: :Lighten,
        clear_mode: :Clear
      ]
    ]
  }

  @native_atoms [
    :ok,
    :error,
    :invalid_batch,
    :invalid_image,
    :invalid_font,
    "nil",
    :render_failed,
    :unsupported_format,
    :commands,
    :op,
    :args,
    :opts,
    :rgba,
    :linear_gradient,
    :radial_gradient,
    :segments,
    :move_to,
    :line_to,
    :quad_to,
    :cubic_to,
    :close
  ]

  @native_refs %{
    rect: ["skia_safe::Canvas::draw_rect", "skia_safe::Canvas::draw_rrect"],
    circle: ["skia_safe::Canvas::draw_circle"],
    line: ["skia_safe::Canvas::draw_line"],
    text: ["skia_safe::Canvas::draw_str", "skia_safe::Font::measure_str"],
    image: [
      "skia_safe::Canvas::draw_image_with_sampling_options",
      "skia_safe::Canvas::draw_image_rect_with_sampling_options"
    ],
    path: ["skia_safe::Canvas::draw_path"],
    clip_rect: ["skia_safe::Canvas::clip_rect", "skia_safe::Canvas::clip_rrect"],
    clip_circle: ["skia_safe::Canvas::clip_path"],
    clip_path: ["skia_safe::Canvas::clip_path"],
    save: ["skia_safe::Canvas::save"],
    save_layer: ["skia_safe::Canvas::save_layer_alpha_f"],
    restore: ["skia_safe::Canvas::restore"],
    translate: ["skia_safe::Canvas::translate"],
    rotate: ["skia_safe::Canvas::rotate"],
    background: ["skia_safe::Canvas::clear"]
  }

  defp render_template(name, assigns) do
    name
    |> template_path()
    |> EEx.eval_file(assigns: assigns)
  end

  defp template_path(name) do
    __DIR__
    |> Path.join("../../priv/codegen/templates/#{name}")
    |> Path.expand()
  end

  @spec generated_atoms() :: String.t()
  def generated_atoms do
    atoms =
      Skia.CommandSpec.all()
      |> Enum.flat_map(fn {name, spec} ->
        option_atoms = spec |> Keyword.get(:opts, []) |> Enum.map(&Keyword.fetch!(&1, :name))
        arg_atoms = spec |> Keyword.get(:args, []) |> Keyword.keys()
        [name, Keyword.get(spec, :op) | option_atoms ++ arg_atoms]
      end)
      |> Kernel.++(@native_atoms)
      |> Kernel.++(@enum_atoms |> Map.values() |> List.flatten())
      |> Enum.reject(&is_nil/1)
      |> Enum.map(&to_string/1)
      |> Enum.uniq()
      |> Enum.sort()

    "generated_atoms.rs"
    |> template_path()
    |> RustQ.render_file!(
      preamble: generated_rust_preamble(),
      splice: [atoms: RustQ.Rustler.atoms(atoms, module: false)]
    )
  end

  @spec generated_enums() :: String.t()
  def generated_enums do
    entries =
      @enum_atoms
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, values} ->
        Rust.const(enum_const_name(name), {:raw, "&[&str]"}, Rust.expr(enum_values(values)),
          vis: :pub
        )
      end)

    decoders =
      @enum_decoders
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map(fn {name, spec} -> enum_decoder(name, spec) end)

    "generated_enums.rs"
    |> template_path()
    |> RustQ.render_file!(
      preamble: generated_rust_preamble(),
      splice: [entries: entries, decoders: decoders]
    )
  end

  defp generated_rust_preamble do
    "// Generated by mix skia.codegen. Do not edit by hand.\n\n"
  end

  defp enum_const_name(name) do
    rust_name = name |> Atom.to_string() |> Macro.camelize()
    "#{Macro.underscore(rust_name) |> String.upcase()}S"
  end

  defp enum_values(values) do
    values = Enum.map_join(values, ", ", &inspect(to_string(&1)))
    "&[#{values}]"
  end

  defp enum_decoder(name, spec) do
    arms =
      spec
      |> Keyword.fetch!(:variants)
      |> Enum.map(fn {atom, variant} ->
        Rust.arm(
          "value if value == atoms::#{atom}()",
          "Ok(#{Rust.type(Keyword.fetch!(spec, :type))}::#{variant})"
        )
      end)
      |> Kernel.++([Rust.arm("_", "Err(rustler::Error::BadArg)")])

    RustQ.render!(
      """
      pub fn __rq_fn_name(value: Atom) -> NifResult<__rq_type!()> {
          match value {
              __rq_arms => unreachable!(),
          }
      }
      """,
      "enum_decoder.rs",
      bind: [fn_name: "decode_#{name}", type: {:type, Keyword.fetch!(spec, :type)}],
      splice: [arms: arms]
    )
    |> Rust.item()
  end

  @spec generated_opts() :: String.t()
  def generated_opts do
    commands =
      Skia.CommandSpec.all()
      |> Enum.reject(fn {_name, spec} -> Keyword.get(spec, :opts, []) == [] end)
      |> Enum.flat_map(fn {name, spec} ->
        struct_name = name |> Atom.to_string() |> Macro.camelize() |> Kernel.<>("Opts")
        opts = Keyword.get(spec, :opts, [])

        RustQ.Rustler.opts_decoder(struct_name,
          lifetime: :a,
          fn: "decode_#{name}_opts",
          fields: Enum.map(opts, &opts_decoder_field/1)
        )
      end)

    "generated_opts.rs"
    |> template_path()
    |> RustQ.render_file!(preamble: generated_rust_preamble(), splice: [commands: commands])
  end

  @spec generated_docs() :: String.t()
  def generated_docs do
    rows =
      Skia.CommandSpec.all()
      |> Enum.map_join("\n", fn {name, spec} ->
        args = spec |> Keyword.get(:args, []) |> format_args()
        opts = spec |> Keyword.get(:opts, []) |> format_opts()
        defaults = spec |> Keyword.get(:defaults, []) |> format_defaults()
        native = name |> native_refs() |> format_native_refs()
        "| `#{name}` | #{args} | #{opts} | #{defaults} | #{native} |"
      end)

    enums =
      @enum_atoms
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map_join("\n", fn {name, values} ->
        values = Enum.map_join(values, ", ", &"`:#{&1}`")
        "- `#{name}`: #{values}"
      end)

    rust_docs = generated_rust_doc_section()

    render_template("commands.md.eex", rows: rows, enums: enums, rust_docs: rust_docs)
  end

  defp opts_decoder_field(opt) do
    {Keyword.fetch!(opt, :name), [type: rust_option_type(opt), decode: option_decoder(opt)]}
  end

  defp rust_option_type(opt) do
    type = Keyword.fetch!(opt, :type)

    if Keyword.get(opt, :required, false) do
      rust_required_type(type)
    else
      rust_optional_type(type)
    end
  end

  defp rust_required_type(:number), do: "f32"
  defp rust_required_type(:boolean), do: "bool"
  defp rust_required_type(:atom), do: "Atom"
  defp rust_required_type(:integer), do: "i64"
  defp rust_required_type(:string), do: "String"
  defp rust_required_type(type) when type in [:color, :path, :image, :font, :term], do: "Term<'a>"
  defp rust_required_type({:tuple, _types}), do: "Term<'a>"

  defp rust_optional_type(:number), do: "Option<f32>"
  defp rust_optional_type(:boolean), do: "Option<bool>"
  defp rust_optional_type(:atom), do: "Option<Atom>"
  defp rust_optional_type(:integer), do: "Option<i64>"
  defp rust_optional_type(:string), do: "Option<String>"

  defp rust_optional_type(type) when type in [:color, :path, :image, :font, :term],
    do: "Option<Term<'a>>"

  defp rust_optional_type({:tuple, _types}), do: "Option<Term<'a>>"

  defp option_decoder(opt) do
    name = Keyword.fetch!(opt, :name)
    type = Keyword.fetch!(opt, :type)
    atom = "atoms::#{name}()"

    if Keyword.get(opt, :required, false) do
      required_decoder(type, atom)
    else
      optional_decoder(type, atom)
    end
  end

  defp required_decoder(:number, atom), do: "opt_f32(opts, #{atom})?"

  defp required_decoder(:boolean, atom),
    do: "opt_bool_option(opts, #{atom})?.ok_or(rustler::Error::BadArg)?"

  defp required_decoder(:atom, atom),
    do: "opt_atom_option(opts, #{atom})?.ok_or(rustler::Error::BadArg)?"

  defp required_decoder(:integer, atom),
    do: "opt_term(opts, #{atom}).ok_or(rustler::Error::BadArg)?.decode::<i64>()?"

  defp required_decoder(:string, atom),
    do: "opt_term(opts, #{atom}).ok_or(rustler::Error::BadArg)?.decode::<String>()?"

  defp required_decoder(type, atom) when type in [:color, :path, :image, :font, :term],
    do: "opt_term(opts, #{atom}).ok_or(rustler::Error::BadArg)?"

  defp required_decoder({:tuple, _types}, atom),
    do: "opt_term(opts, #{atom}).ok_or(rustler::Error::BadArg)?"

  defp optional_decoder(:number, atom), do: "opt_f32_option(opts, #{atom})?"
  defp optional_decoder(:boolean, atom), do: "opt_bool_option(opts, #{atom})?"
  defp optional_decoder(:atom, atom), do: "opt_atom_option(opts, #{atom})?"

  defp optional_decoder(:integer, atom),
    do:
      "match opt_term(opts, #{atom}) { Some(term) => Some(term.decode::<i64>()?), None => None }"

  defp optional_decoder(:string, atom),
    do:
      "match opt_term(opts, #{atom}) { Some(term) => Some(term.decode::<String>()?), None => None }"

  defp optional_decoder(type, atom) when type in [:color, :path, :image, :font, :term],
    do: "opt_term(opts, #{atom})"

  defp optional_decoder({:tuple, _types}, atom), do: "opt_term(opts, #{atom})"

  defp format_args([]), do: "—"

  defp format_args(args) do
    args
    |> Enum.map_join("<br>", fn {name, type} -> "`#{name}: #{format_type(type)}`" end)
  end

  defp format_opts([]), do: "—"

  defp format_opts(opts) do
    opts
    |> Enum.map_join("<br>", fn opt ->
      name = Keyword.fetch!(opt, :name)
      type = opt |> Keyword.fetch!(:type) |> format_type()
      required = if Keyword.get(opt, :required, false), do: " required", else: ""
      "`#{name}: #{type}`#{required}"
    end)
  end

  defp format_defaults([]), do: "—"

  defp format_defaults(defaults) do
    defaults
    |> Enum.map_join("<br>", fn {name, value} -> "`#{name}: #{inspect(value)}`" end)
  end

  defp native_refs(command), do: Map.get(@native_refs, command, [])

  defp format_native_refs([]), do: "—"

  defp format_native_refs(refs) do
    refs
    |> Enum.map_join("<br>", &"`#{&1}`")
  end

  defp generated_rust_doc_section do
    docs =
      @native_refs
      |> Map.values()
      |> List.flatten()
      |> Enum.uniq()
      |> Enum.sort()
      |> Enum.flat_map(&rust_doc_entry/1)

    if docs == [] do
      "## Rust doc excerpts\n\nNo local `skia-safe` source docs found.\n"
    else
      IO.iodata_to_binary(["## Rust doc excerpts\n\n", Enum.join(docs, "\n\n")])
    end
  end

  defp rust_doc_entry(ref) do
    case rust_doc_snippet(ref) do
      nil -> []
      snippet -> ["### `#{ref}`\n\n#{snippet}"]
    end
  end

  defp rust_doc_snippet("skia_safe::" <> path) do
    [module, function] = String.split(path, "::", parts: 2)

    with {:ok, source} <- rust_source(module),
         {:ok, docs} <- extract_rust_docs(source, function) do
      docs
      |> Enum.take(4)
      |> Enum.map_join("\n", &"> #{&1}")
    else
      _ -> nil
    end
  end

  defp rust_source("Canvas"), do: read_skia_safe_source("core/canvas.rs")
  defp rust_source("Font"), do: read_skia_safe_source("core/font.rs")
  defp rust_source(_module), do: :error

  defp read_skia_safe_source(relative_path) do
    pattern =
      Path.join([
        System.user_home!(),
        ".cargo/registry/src/*/skia-safe-*/src",
        relative_path
      ])

    pattern
    |> Path.wildcard()
    |> Enum.sort(:desc)
    |> List.first()
    |> case do
      nil -> :error
      path -> File.read(path)
    end
  end

  defp extract_rust_docs(source, function) do
    lines = String.split(source, "\n")
    index = Enum.find_index(lines, &String.contains?(&1, "fn #{function}"))

    if index do
      docs =
        lines
        |> Enum.take(index)
        |> Enum.reverse()
        |> Enum.take_while(&(String.trim_leading(&1) |> String.starts_with?("///")))
        |> Enum.reverse()
        |> Enum.map(&clean_rust_doc_line/1)
        |> Enum.reject(&(&1 == ""))

      if docs == [], do: :error, else: {:ok, docs}
    else
      :error
    end
  end

  defp clean_rust_doc_line(line) do
    line
    |> String.trim_leading()
    |> String.replace_prefix("///", "")
    |> String.trim()
  end

  defp format_type({:tuple, types}) do
    inner = Enum.map_join(types, ", ", &format_type/1)
    "{#{inner}}"
  end

  defp format_type(type), do: to_string(type)
end
