// Generated by mix skia.codegen. Do not edit by hand.

fn draw_translate_impl<'a>(
    surface: &mut skia_safe::Surface,
    opts: generated_opts::TranslateOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    surface.canvas().translate((opts.x, opts.y));
    Ok(())
}
fn draw_scale_impl<'a>(
    surface: &mut skia_safe::Surface,
    opts: generated_opts::ScaleOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    surface.canvas().scale((opts.x, opts.y));
    Ok(())
}
fn draw_rotate_impl<'a>(
    surface: &mut skia_safe::Surface,
    opts: generated_opts::RotateOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    surface.canvas().rotate(opts.degrees, None);
    Ok(())
}
fn draw_rotate_at_impl<'a>(
    surface: &mut skia_safe::Surface,
    opts: generated_opts::RotateAtOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    surface.canvas().rotate(opts.degrees, Some(Point::new(opts.x, opts.y)));
    Ok(())
}
fn draw_concat_impl<'a>(
    surface: &mut skia_safe::Surface,
    opts: generated_opts::ConcatOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    let matrix = matrix_from_term(opts.matrix)?;
    surface.canvas().concat(&matrix);
    Ok(())
}
