// Generated by mix skia.codegen. Do not edit by hand.

#[allow(unused_variables)]
fn clip_circle<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_clip_circle_opts(&opts)?;
    return clip_circle_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn clip_path<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_clip_path_opts(&opts)?;
    return clip_path_impl(surface, args, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn clip_rect<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_clip_rect_opts(&opts)?;
    return clip_rect_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_circle<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_circle_opts(&opts)?;
    return draw_circle_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_clear<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    return draw_clear_impl(surface, args);
}
#[allow(unused_variables)]
fn draw_image<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_image_opts(&opts)?;
    return draw_image_impl(surface, args, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_line<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_line_opts(&opts)?;
    return draw_line_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_path<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_path_opts(&opts)?;
    return draw_path_impl(surface, args, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_rect<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rect_opts(&opts)?;
    return draw_rect_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_restore<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    return draw_restore_impl(surface);
}
#[allow(unused_variables)]
fn draw_rotate<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rotate_opts(&opts)?;
    return draw_rotate_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_save<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    return draw_save_impl(surface);
}
#[allow(unused_variables)]
fn draw_save_layer<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_save_layer_opts(&opts)?;
    return draw_save_layer_impl(surface, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_text<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_text_opts(&opts)?;
    return draw_text_impl(surface, args, decoded_opts, &opts);
}
#[allow(unused_variables)]
fn draw_translate<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_translate_opts(&opts)?;
    return draw_translate_impl(surface, decoded_opts, &opts);
}
