// Generated by mix skia.codegen. Do not edit by hand.

fn build_path(path_term: Term) -> NifResult<skia_safe::Path> {
    if let Ok(svg_term) = path_term.map_get(atoms::svg()) {
        if let Ok(svg) = svg_term.decode::<String>() {
            return skia_safe::Path::from_svg(svg).ok_or(rustler::Error::BadArg);
        }
    }
    let segments = path_term.map_get(atoms::segments())?.decode::<Vec<Term>>()?;
    let mut builder = PathBuilder::new();
    for segment in segments.into_iter().rev() {
        if let Ok(op) = segment.decode::<Atom>() {
            if op == atoms::close() {
                builder.close();
            }
        } else if let Ok((op, x, y)) = segment.decode::<(Atom, f64, f64)>() {
            if op == atoms::move_to() {
                builder.move_to((x as f32, y as f32));
            } else if op == atoms::line_to() {
                builder.line_to((x as f32, y as f32));
            } else if op == atoms::r_move_to() {
                builder.r_move_to((x as f32, y as f32));
            } else if op == atoms::r_line_to() {
                builder.r_line_to((x as f32, y as f32));
            }
        } else if let Ok((op, cx, cy, x, y)) = segment
            .decode::<(Atom, f64, f64, f64, f64)>()
        {
            if op == atoms::quad_to() {
                builder.quad_to((cx as f32, cy as f32), (x as f32, y as f32));
            } else if op == atoms::r_quad_to() {
                builder.r_quad_to((cx as f32, cy as f32), (x as f32, y as f32));
            }
        } else if let Ok((op, cx, cy, x, y, weight)) = segment
            .decode::<(Atom, f64, f64, f64, f64, f64)>()
        {
            if op == atoms::conic_to() {
                builder
                    .conic_to(
                        (cx as f32, cy as f32),
                        (x as f32, y as f32),
                        weight as f32,
                    );
            } else if op == atoms::r_conic_to() {
                builder
                    .r_conic_to(
                        (cx as f32, cy as f32),
                        (x as f32, y as f32),
                        weight as f32,
                    );
            }
        } else if let Ok((op, c1x, c1y, c2x, c2y, x, y)) = segment
            .decode::<(Atom, f64, f64, f64, f64, f64, f64)>()
        {
            if op == atoms::cubic_to() {
                builder
                    .cubic_to(
                        (c1x as f32, c1y as f32),
                        (c2x as f32, c2y as f32),
                        (x as f32, y as f32),
                    );
            } else if op == atoms::r_cubic_to() {
                builder
                    .r_cubic_to(
                        (c1x as f32, c1y as f32),
                        (c2x as f32, c2y as f32),
                        (x as f32, y as f32),
                    );
            }
        }
    }
    Ok(builder.detach())
}
