// Generated by mix skia.codegen. Do not edit by hand.

use skia_safe::Canvas;
use atoms as Atoms;
use generated_opts as GeneratedOpts;

fn clip_circle<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_clip_circle_opts(&opts)?;
    clip_circle_impl(canvas, decoded_opts, &opts)
}
fn clip_path<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_clip_path_opts(&opts)?;
    clip_path_impl(canvas, args, decoded_opts, &opts)
}
fn clip_rect<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_clip_rect_opts(&opts)?;
    clip_rect_impl(canvas, decoded_opts, &opts)
}
fn draw_arc<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_arc_opts(&opts)?;
    draw_arc_impl(canvas, decoded_opts, &opts)
}
fn draw_circle<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_circle_opts(&opts)?;
    draw_circle_impl(canvas, decoded_opts, &opts)
}
fn draw_clear<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    draw_clear_impl(canvas, args)
}
fn draw_concat<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_concat_opts(&opts)?;
    draw_concat_impl(canvas, decoded_opts, &opts)
}
fn draw_image<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_image_opts(&opts)?;
    draw_image_impl(canvas, args, decoded_opts, &opts)
}
fn draw_line<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_line_opts(&opts)?;
    draw_line_impl(canvas, decoded_opts, &opts)
}
fn draw_oval<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_oval_opts(&opts)?;
    draw_oval_impl(canvas, decoded_opts, &opts)
}
fn draw_path<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_path_opts(&opts)?;
    draw_path_impl(canvas, args, decoded_opts, &opts)
}
fn draw_path_op<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_path_op_opts(&opts)?;
    draw_path_op_impl(canvas, args, decoded_opts, &opts)
}
fn draw_path_outline<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_path_outline_opts(&opts)?;
    draw_path_outline_impl(canvas, args, decoded_opts, &opts)
}
fn draw_picture<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_picture_opts(&opts)?;
    draw_picture_impl(canvas, args, decoded_opts, &opts)
}
fn draw_rect<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_rect_opts(&opts)?;
    draw_rect_impl(canvas, decoded_opts, &opts)
}
fn draw_restore<'a>(canvas: &Canvas, _command: Term<'a>) -> NifResult<()> {
    draw_restore_impl(canvas)
}
fn draw_rotate<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_rotate_opts(&opts)?;
    draw_rotate_impl(canvas, decoded_opts, &opts)
}
fn draw_rotate_at<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_rotate_at_opts(&opts)?;
    draw_rotate_at_impl(canvas, decoded_opts, &opts)
}
fn draw_save<'a>(canvas: &Canvas, _command: Term<'a>) -> NifResult<()> {
    draw_save_impl(canvas)
}
fn draw_save_layer<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_save_layer_opts(&opts)?;
    draw_save_layer_impl(canvas, decoded_opts, &opts)
}
fn draw_scale<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_scale_opts(&opts)?;
    draw_scale_impl(canvas, decoded_opts, &opts)
}
fn draw_text<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_text_opts(&opts)?;
    draw_text_impl(canvas, args, decoded_opts, &opts)
}
fn draw_text_blob<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_text_blob_opts(&opts)?;
    draw_text_blob_impl(canvas, args, decoded_opts, &opts)
}
fn draw_translate<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_translate_opts(&opts)?;
    draw_translate_impl(canvas, decoded_opts, &opts)
}
fn draw_vertices<'a>(canvas: &Canvas, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(Atoms::args())?.decode::<Vec<Term<'a>>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = GeneratedOpts::decode_vertices_opts(&opts)?;
    draw_vertices_impl(canvas, args, decoded_opts, &opts)
}
