// Generated by mix skia.codegen. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn render_png<'a>(env: Env<'a>, batch: Term<'a>) -> NifResult<Term<'a>> {
    render_png_impl(env, batch)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn render_rgba<'a>(env: Env<'a>, batch: Term<'a>) -> NifResult<Term<'a>> {
    render_rgba_impl(env, batch)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn render_jpeg<'a>(env: Env<'a>, batch: Term<'a>, quality: u32) -> NifResult<Term<'a>> {
    render_jpeg_impl(env, batch, quality)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn render_webp<'a>(env: Env<'a>, batch: Term<'a>, quality: u32) -> NifResult<Term<'a>> {
    render_webp_impl(env, batch, quality)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn decode_image<'a>(env: Env<'a>, bytes: Binary<'a>) -> NifResult<Term<'a>> {
    decode_image_impl(env, bytes)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn encode_image<'a>(
    env: Env<'a>,
    image_term: Term<'a>,
    format: Atom,
    quality: u32,
) -> NifResult<Term<'a>> {
    encode_image_impl(env, image_term, format, quality)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn resize_image<'a>(
    env: Env<'a>,
    image_term: Term<'a>,
    width: i32,
    height: i32,
) -> NifResult<Term<'a>> {
    resize_image_impl(env, image_term, width, height)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn crop_image<'a>(
    env: Env<'a>,
    image_term: Term<'a>,
    source: (f64, f64, f64, f64),
) -> NifResult<Term<'a>> {
    crop_image_impl(env, image_term, source)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn load_font<'a>(env: Env<'a>, bytes: Binary<'a>) -> NifResult<Term<'a>> {
    load_font_impl(env, bytes)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn measure_text<'a>(
    env: Env<'a>,
    text: String,
    font_term: Term<'a>,
    size: f64,
) -> NifResult<Term<'a>> {
    measure_text_impl(env, text, font_term, size)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn path_to_svg<'a>(env: Env<'a>, path_term: Term<'a>) -> NifResult<Term<'a>> {
    path_to_svg_impl(env, path_term)
}
