// Generated by mix skia.codegen. Do not edit by hand.

fn draw_translate_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::TranslateOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.translate((opts.x, opts.y));
    Ok(())
}
fn draw_scale_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::ScaleOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.scale((opts.x, opts.y));
    Ok(())
}
fn draw_rotate_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::RotateOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.rotate(opts.degrees, None);
    Ok(())
}
fn draw_rotate_at_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::RotateAtOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.rotate(opts.degrees, Some(Point::new(opts.x, opts.y)));
    Ok(())
}
fn draw_concat_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::ConcatOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    let matrix = matrix_from_term(opts.matrix)?;
    canvas.concat(&matrix);
    Ok(())
}
