// Generated by mix skia.codegen. Do not edit by hand.

pub struct EncodedFont {
    pub typeface: skia_safe::Typeface,
}
pub struct EncodedImage {
    pub image: Image,
}
pub struct EncodedPicture {
    pub bytes: Vec<u8>,
    pub picture: Picture,
}
pub struct EncodedRuntimeEffect {
    pub source: String,
}
pub struct EncodedTextBlob {
    pub blob: TextBlob,
}
#[rustler::resource_impl]
impl rustler::Resource for EncodedFont {}
#[rustler::resource_impl]
impl rustler::Resource for EncodedImage {}
#[rustler::resource_impl]
impl rustler::Resource for EncodedPicture {}
#[rustler::resource_impl]
impl rustler::Resource for EncodedRuntimeEffect {}
#[rustler::resource_impl]
impl rustler::Resource for EncodedTextBlob {}
fn decode_encoded_image_ref<'a>(term: Term<'a>) -> NifResult<ResourceArc<EncodedImage>> {
    term.map_get(Atom::from_bytes(term.get_env(), b"ref")?)?
        .decode::<ResourceArc<EncodedImage>>()
}
fn decode_encoded_font_ref<'a>(term: Term<'a>) -> NifResult<ResourceArc<EncodedFont>> {
    term.map_get(Atom::from_bytes(term.get_env(), b"ref")?)?
        .decode::<ResourceArc<EncodedFont>>()
}
fn decode_encoded_picture_ref<'a>(
    term: Term<'a>,
) -> NifResult<ResourceArc<EncodedPicture>> {
    term.map_get(Atom::from_bytes(term.get_env(), b"ref")?)?
        .decode::<ResourceArc<EncodedPicture>>()
}
fn decode_encoded_text_blob_ref<'a>(
    term: Term<'a>,
) -> NifResult<ResourceArc<EncodedTextBlob>> {
    term.map_get(Atom::from_bytes(term.get_env(), b"ref")?)?
        .decode::<ResourceArc<EncodedTextBlob>>()
}
fn decode_encoded_runtime_effect_ref<'a>(
    term: Term<'a>,
) -> NifResult<ResourceArc<EncodedRuntimeEffect>> {
    term.map_get(Atom::from_bytes(term.get_env(), b"ref")?)?
        .decode::<ResourceArc<EncodedRuntimeEffect>>()
}
