// Generated by mix skia.codegen. Do not edit by hand.

fn clip_circle<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_clip_circle_opts(&opts)?;
    clip_circle_impl(surface, decoded_opts, &opts)
}
fn clip_path<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_clip_path_opts(&opts)?;
    clip_path_impl(surface, args, decoded_opts, &opts)
}
fn clip_rect<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_clip_rect_opts(&opts)?;
    clip_rect_impl(surface, decoded_opts, &opts)
}
fn draw_arc<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_arc_opts(&opts)?;
    draw_arc_impl(surface, decoded_opts, &opts)
}
fn draw_circle<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_circle_opts(&opts)?;
    draw_circle_impl(surface, decoded_opts, &opts)
}
fn draw_clear<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    draw_clear_impl(surface, args)
}
fn draw_concat<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_concat_opts(&opts)?;
    draw_concat_impl(surface, decoded_opts, &opts)
}
fn draw_image<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_image_opts(&opts)?;
    draw_image_impl(surface, args, decoded_opts, &opts)
}
fn draw_line<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_line_opts(&opts)?;
    draw_line_impl(surface, decoded_opts, &opts)
}
fn draw_oval<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_oval_opts(&opts)?;
    draw_oval_impl(surface, decoded_opts, &opts)
}
fn draw_path<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_path_opts(&opts)?;
    draw_path_impl(surface, args, decoded_opts, &opts)
}
fn draw_path_op<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_path_op_opts(&opts)?;
    draw_path_op_impl(surface, args, decoded_opts, &opts)
}
fn draw_rect<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rect_opts(&opts)?;
    draw_rect_impl(surface, decoded_opts, &opts)
}
fn draw_restore<'a>(
    surface: &mut skia_safe::Surface,
    _command: Term<'a>,
) -> NifResult<()> {
    draw_restore_impl(surface)
}
fn draw_rotate<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rotate_opts(&opts)?;
    draw_rotate_impl(surface, decoded_opts, &opts)
}
fn draw_rotate_at<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rotate_at_opts(&opts)?;
    draw_rotate_at_impl(surface, decoded_opts, &opts)
}
fn draw_save<'a>(surface: &mut skia_safe::Surface, _command: Term<'a>) -> NifResult<()> {
    draw_save_impl(surface)
}
fn draw_save_layer<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_save_layer_opts(&opts)?;
    draw_save_layer_impl(surface, decoded_opts, &opts)
}
fn draw_scale<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_scale_opts(&opts)?;
    draw_scale_impl(surface, decoded_opts, &opts)
}
fn draw_text<'a>(surface: &mut skia_safe::Surface, command: Term<'a>) -> NifResult<()> {
    let args = command.map_get(atoms::args())?.decode::<Vec<Term>>()?;
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_text_opts(&opts)?;
    draw_text_impl(surface, args, decoded_opts, &opts)
}
fn draw_translate<'a>(
    surface: &mut skia_safe::Surface,
    command: Term<'a>,
) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_translate_opts(&opts)?;
    draw_translate_impl(surface, decoded_opts, &opts)
}
