// Generated by mix skia.codegen. Do not edit by hand.

struct EncodedImage {
    pub bytes: Vec<u8>,
}
#[rustler::resource_impl]
impl rustler::Resource for EncodedImage {}
struct EncodedFont {
    pub bytes: Vec<u8>,
}
#[rustler::resource_impl]
impl rustler::Resource for EncodedFont {}
