// Generated by mix skia.codegen. Do not edit by hand.

fn draw_translate<'a>(canvas: &skia_safe::Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_translate_opts(&opts)?;
    draw_translate_impl(canvas, decoded_opts, &opts)
}
fn draw_translate_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::TranslateOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.translate((opts.x, opts.y));
    Ok(())
}
fn draw_scale<'a>(canvas: &skia_safe::Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_scale_opts(&opts)?;
    draw_scale_impl(canvas, decoded_opts, &opts)
}
fn draw_scale_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::ScaleOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.scale((opts.x, opts.y));
    Ok(())
}
fn draw_rotate<'a>(canvas: &skia_safe::Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rotate_opts(&opts)?;
    draw_rotate_impl(canvas, decoded_opts, &opts)
}
fn draw_rotate_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::RotateOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.rotate(opts.degrees, None);
    Ok(())
}
fn draw_rotate_at<'a>(canvas: &skia_safe::Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_rotate_at_opts(&opts)?;
    draw_rotate_at_impl(canvas, decoded_opts, &opts)
}
fn draw_rotate_at_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::RotateAtOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    canvas.rotate(opts.degrees, Some(Point::new(opts.x, opts.y)));
    Ok(())
}
fn draw_concat<'a>(canvas: &skia_safe::Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_concat_opts(&opts)?;
    draw_concat_impl(canvas, decoded_opts, &opts)
}
fn draw_concat_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::ConcatOpts<'a>,
    _raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    let matrix = matrix_from_term(opts.matrix)?;
    canvas.concat(&matrix);
    Ok(())
}
