// Generated by mix skia.codegen. Do not edit by hand.

fn draw_save<'a>(canvas: &skia_safe::Canvas, _command: Term<'a>) -> NifResult<()> {
    canvas.save();
    Ok(())
}
fn draw_restore<'a>(canvas: &skia_safe::Canvas, _command: Term<'a>) -> NifResult<()> {
    canvas.restore();
    Ok(())
}
fn draw_save_layer<'a>(canvas: &skia_safe::Canvas, command: Term<'a>) -> NifResult<()> {
    let opts = decode_opts(command)?;
    let decoded_opts = generated_opts::decode_save_layer_opts(&opts)?;
    draw_save_layer_impl(canvas, decoded_opts, &opts)
}
fn draw_save_layer_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::SaveLayerOpts<'a>,
    raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    let bounds = match opts.bounds {
        Some(term) => Some(rect_from_term(term)?),
        None => None,
    };
    let mut paint = Paint::default();
    let alpha = (opts.opacity.unwrap_or(1.0).clamp(0.0, 1.0) * 255.0).round() as u8;
    paint.set_alpha(alpha);
    apply_blend_mode(&mut paint, raw_opts)?;
    if let Some(sigma) = opts.blur {
        if let Some(filter) = image_filters::blur(
            (sigma, sigma),
            TileMode::Decal,
            None,
            None,
        ) {
            paint.set_image_filter(filter);
        }
    }
    if let Some(term) = opts.image_filter {
        let filter = decode_image_filter(term)?;
        paint.set_image_filter(filter);
    }
    let backdrop = match opts.backdrop_filter {
        Some(term) => Some(decode_image_filter(term)?),
        None => None,
    };
    let rec = SaveLayerRec::default().paint(&paint);
    let rec = match bounds.as_ref() {
        Some(bounds) => rec.bounds(bounds),
        None => rec,
    };
    let rec = match backdrop.as_ref() {
        Some(filter) => rec.backdrop(filter),
        None => rec,
    };
    canvas.save_layer(&rec);
    Ok(())
}
