// Generated by mix skia.codegen. Do not edit by hand.

fn decode_paint(term: Term) -> NifResult<Paint> {
    if let Ok(color) = decode_color(term) {
        return Ok(fill_paint(color));
    }
    if let Ok((tag, from, to, stops, tile_mode, matrix_term)) = term
        .decode::<(Atom, (f64, f64), (f64, f64), Vec<Term>, Atom, Term)>()
    {
        if tag == atoms::linear_gradient() {
            let (colors, positions) = decode_gradient_stops(stops)?;
            let tile_mode = generated_enums::decode_tile_mode(tile_mode)?;
            let matrix = optional_matrix_from_term(matrix_term)?;
            let mut paint = Paint::default();
            paint.set_anti_alias(true).set_style(PaintStyle::Fill);
            if let Some(shader) = Shader::linear_gradient(
                ((from.0 as f32, from.1 as f32), (to.0 as f32, to.1 as f32)),
                colors.as_slice(),
                positions.as_deref(),
                tile_mode,
                None,
                matrix.as_ref(),
            ) {
                paint.set_shader(shader);
            }
            return Ok(paint);
        }
    }
    if let Ok((tag, center, radius, stops, tile_mode, matrix_term)) = term
        .decode::<(Atom, (f64, f64), f64, Vec<Term>, Atom, Term)>()
    {
        if tag == atoms::radial_gradient() {
            let (colors, positions) = decode_gradient_stops(stops)?;
            let tile_mode = generated_enums::decode_tile_mode(tile_mode)?;
            let matrix = optional_matrix_from_term(matrix_term)?;
            let mut paint = Paint::default();
            paint.set_anti_alias(true).set_style(PaintStyle::Fill);
            if let Some(shader) = Shader::radial_gradient(
                (center.0 as f32, center.1 as f32),
                radius as f32,
                colors.as_slice(),
                positions.as_deref(),
                tile_mode,
                None,
                matrix.as_ref(),
            ) {
                paint.set_shader(shader);
            }
            return Ok(paint);
        }
    }
    if let Ok(
        (tag, center, start_degrees, end_degrees, stops, tile_mode, matrix_term),
    ) = term.decode::<(Atom, (f64, f64), f64, f64, Vec<Term>, Atom, Term)>()
    {
        if tag == atoms::sweep_gradient() {
            let (colors, positions) = decode_gradient_stops(stops)?;
            let tile_mode = generated_enums::decode_tile_mode(tile_mode)?;
            let matrix = optional_matrix_from_term(matrix_term)?;
            let mut paint = Paint::default();
            paint.set_anti_alias(true).set_style(PaintStyle::Fill);
            if let Some(shader) = Shader::sweep_gradient(
                (center.0 as f32, center.1 as f32),
                colors.as_slice(),
                positions.as_deref(),
                tile_mode,
                Some((start_degrees as f32, end_degrees as f32)),
                None,
                matrix.as_ref(),
            ) {
                paint.set_shader(shader);
            }
            return Ok(paint);
        }
    }
    if let Ok((tag, image_term, tile_x, tile_y, sampling, matrix_term)) = term
        .decode::<(Atom, Term, Atom, Atom, Atom, Term)>()
    {
        if tag == atoms::image_shader() {
            let image = image_from_term(image_term)?;
            let tile_x = generated_enums::decode_tile_mode(tile_x)?;
            let tile_y = generated_enums::decode_tile_mode(tile_y)?;
            let sampling = SamplingOptions::from(
                generated_enums::decode_sampling(sampling)?,
            );
            let matrix = optional_matrix_from_term(matrix_term)?;
            let mut paint = Paint::default();
            paint.set_anti_alias(true).set_style(PaintStyle::Fill);
            if let Some(shader) = image
                .to_shader((tile_x, tile_y), sampling, matrix.as_ref())
            {
                paint.set_shader(shader);
            }
            return Ok(paint);
        }
    }
    Err(rustler::Error::BadArg)
}
fn decode_image_filter(term: Term) -> NifResult<skia_safe::ImageFilter> {
    if let Ok((tag, sigma_x, sigma_y, tile_mode)) = term
        .decode::<(Atom, f64, f64, Atom)>()
    {
        if tag == atoms::blur_filter() {
            let tile_mode = generated_enums::decode_tile_mode(tile_mode)?;
            return image_filters::blur(
                    (sigma_x as f32, sigma_y as f32),
                    tile_mode,
                    None,
                    None,
                )
                .ok_or(rustler::Error::BadArg);
        }
    }
    if let Ok((tag, outer, inner)) = term.decode::<(Atom, Term, Term)>() {
        if tag == atoms::compose_filter() {
            return image_filters::compose(
                    decode_image_filter(outer)?,
                    decode_image_filter(inner)?,
                )
                .ok_or(rustler::Error::BadArg);
        }
    }
    if let Ok((tag, x, y, input_term)) = term.decode::<(Atom, f64, f64, Term)>() {
        if tag == atoms::offset_filter() {
            return image_filters::offset(
                    (x as f32, y as f32),
                    optional_image_filter_from_term(input_term)?,
                    None,
                )
                .ok_or(rustler::Error::BadArg);
        }
    }
    if let Ok((tag, dx, dy, sigma_x, sigma_y, color_term, shadow_opts)) = term
        .decode::<(Atom, f64, f64, f64, f64, Term, Term)>()
    {
        if tag == atoms::drop_shadow_filter() {
            let (input_term, shadow_only) = shadow_opts.decode::<(Term, bool)>()?;
            let color = decode_color(color_term)?;
            let input = optional_image_filter_from_term(input_term)?;
            let filter = if shadow_only {
                image_filters::drop_shadow_only(
                    (dx as f32, dy as f32),
                    (sigma_x as f32, sigma_y as f32),
                    color,
                    None,
                    input,
                    None,
                )
            } else {
                image_filters::drop_shadow(
                    (dx as f32, dy as f32),
                    (sigma_x as f32, sigma_y as f32),
                    color,
                    None,
                    input,
                    None,
                )
            };
            return filter.ok_or(rustler::Error::BadArg);
        }
    }
    if let Ok((tag, op, radius_x, radius_y, input_term)) = term
        .decode::<(Atom, Atom, f64, f64, Term)>()
    {
        if tag == atoms::morphology_filter() {
            let input = optional_image_filter_from_term(input_term)?;
            let filter = if op == atoms::dilate() {
                image_filters::dilate((radius_x as f32, radius_y as f32), input, None)
            } else if op == atoms::erode() {
                image_filters::erode((radius_x as f32, radius_y as f32), input, None)
            } else {
                return Err(rustler::Error::BadArg);
            };
            return filter.ok_or(rustler::Error::BadArg);
        }
    }
    Err(rustler::Error::BadArg)
}
fn optional_image_filter_from_term(
    term: Term,
) -> NifResult<Option<skia_safe::ImageFilter>> {
    if term.decode::<Atom>().is_ok_and(|atom| atom == atoms::nil()) {
        Ok(None)
    } else {
        Ok(Some(decode_image_filter(term)?))
    }
}
fn optional_matrix_from_term(matrix_term: Term) -> NifResult<Option<Matrix>> {
    if matrix_term.decode::<Atom>().is_ok_and(|atom| atom == atoms::nil()) {
        Ok(None)
    } else {
        Ok(Some(matrix_from_term(matrix_term)?))
    }
}
fn decode_gradient_stops(stops: Vec<Term>) -> NifResult<(Vec<Color>, Option<Vec<f32>>)> {
    let mut colors = Vec::with_capacity(stops.len());
    let mut positions = Vec::with_capacity(stops.len());
    let mut explicit_positions = true;
    for stop in stops {
        if let Ok((tag, color_term, position)) = stop.decode::<(Atom, Term, f64)>() {
            if tag == atoms::gradient_stop() {
                colors.push(decode_color(color_term)?);
                positions.push(position as f32);
                continue;
            }
        }
        explicit_positions = false;
        colors.push(decode_color(stop)?);
    }
    Ok((colors, if explicit_positions { Some(positions) } else { None }))
}
fn decode_color(term: Term) -> NifResult<Color> {
    let (tag, red, green, blue, alpha) = term.decode::<(Atom, u8, u8, u8, u8)>()?;
    if tag == atoms::rgba() {
        Ok(Color::from_argb(alpha, red, green, blue))
    } else {
        Err(rustler::Error::BadArg)
    }
}
