// Generated by mix skia.codegen. Do not edit by hand.

#![allow(dead_code)]
use rustler::{Atom, NifResult};
use skia_safe::{paint, BlendMode, FilterMode, PathFillType};
use super::atoms;
pub const BLEND_MODES: &[&str] = &[
    "src_over",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "clear_mode",
];
pub const FILL_RULES: &[&str] = &["winding", "even_odd"];
pub const SAMPLINGS: &[&str] = &["nearest", "linear"];
pub const STROKE_CAPS: &[&str] = &["butt", "round", "square"];
pub const STROKE_JOINS: &[&str] = &["miter", "round", "bevel"];
pub fn decode_blend_mode(value: Atom) -> NifResult<BlendMode> {
    match value {
        value if value == atoms::src_over() => Ok(BlendMode::SrcOver),
        value if value == atoms::multiply() => Ok(BlendMode::Multiply),
        value if value == atoms::screen() => Ok(BlendMode::Screen),
        value if value == atoms::overlay() => Ok(BlendMode::Overlay),
        value if value == atoms::darken() => Ok(BlendMode::Darken),
        value if value == atoms::lighten() => Ok(BlendMode::Lighten),
        value if value == atoms::clear_mode() => Ok(BlendMode::Clear),
        _ => Err(rustler::Error::BadArg),
    }
}
pub fn decode_fill_rule(value: Atom) -> NifResult<PathFillType> {
    match value {
        value if value == atoms::winding() => Ok(PathFillType::Winding),
        value if value == atoms::even_odd() => Ok(PathFillType::EvenOdd),
        _ => Err(rustler::Error::BadArg),
    }
}
pub fn decode_sampling(value: Atom) -> NifResult<FilterMode> {
    match value {
        value if value == atoms::nearest() => Ok(FilterMode::Nearest),
        value if value == atoms::linear() => Ok(FilterMode::Linear),
        _ => Err(rustler::Error::BadArg),
    }
}
pub fn decode_stroke_cap(value: Atom) -> NifResult<paint::Cap> {
    match value {
        value if value == atoms::butt() => Ok(paint::Cap::Butt),
        value if value == atoms::round() => Ok(paint::Cap::Round),
        value if value == atoms::square() => Ok(paint::Cap::Square),
        _ => Err(rustler::Error::BadArg),
    }
}
pub fn decode_stroke_join(value: Atom) -> NifResult<paint::Join> {
    match value {
        value if value == atoms::miter() => Ok(paint::Join::Miter),
        value if value == atoms::round() => Ok(paint::Join::Round),
        value if value == atoms::bevel() => Ok(paint::Join::Bevel),
        _ => Err(rustler::Error::BadArg),
    }
}
