// Generated by mix skia.codegen. Do not edit by hand.

#![allow(dead_code)]
pub const BLEND_MODES: &[&str] = &[
    "src_over",
    "multiply",
    "screen",
    "overlay",
    "darken",
    "lighten",
    "clear_mode",
];
pub const FILL_RULES: &[&str] = &["winding", "even_odd"];
pub const SAMPLINGS: &[&str] = &["nearest", "linear"];
pub const STROKE_CAPS: &[&str] = &["butt", "round", "square"];
pub const STROKE_JOINS: &[&str] = &["miter", "round", "bevel"];
