// Generated by mix skia.codegen. Do not edit by hand.

rustler::atoms! {
    antialias, args, background, bevel, blend_mode, butt, circle, clear, clear_mode,
    clip_circle, clip_path, clip_rect, close, color, commands, cubic_to, darken, degrees,
    error, even_odd, fill, fill_rule, font, from, height, image, invalid_batch,
    invalid_font, invalid_image, lighten, line, line_to, linear, linear_gradient, miter,
    move_to, multiply, nearest, nil, ok, op, opacity, opts, overlay, path, pop_style,
    push_style, quad_to, radial_gradient, radius, rect, render_failed, restore, rgba,
    rotate, round, sampling, save, save_layer, screen, segments, size, source, square,
    src_over, stroke, stroke_cap, stroke_join, stroke_miter, stroke_width, style, text,
    to, translate, unsupported_format, weight, width, winding, x, y,
}
