// Generated by mix skia.codegen. Do not edit by hand.

rustler::atoms! {
    a, align, antialias, arc, args, astc, avif, b, background, bevel, blend_mode, blur,
    blur_filter, bmp, bounds, butt, center, circle, clamp, clear, clip_circle, clip_path,
    clip_rect, close, color, color_burn, color_dodge, commands, compose_filter, concat,
    cubic_to, darken, decal, degrees, difference, dilate, direction, dng,
    drop_shadow_filter, dst, dst_a_top, dst_in, dst_out, dst_over, erode, error,
    even_odd, exclusion, fill, fill_rule, font, font_family, from, gif, gradient_stop,
    hard_light, heif, height, hue, ico, image, image_filter, image_shader, intersect,
    invalid_batch, invalid_font, invalid_image, inverse_even_odd, inverse_winding, jpeg,
    jpegxl, justify, ktx, left, lighten, line, line_height, line_to, linear,
    linear_gradient, ltr, luminosity, matrix, mirror, miter, modulate, morphology_filter,
    move_to, multiply, nearest, nil, offset_filter, ok, op, opacity, opts, outline_width,
    oval, overlay, path, path_op, path_outline, pkm, plus, png, pop_style, push_style,
    quad_to, radial_gradient, radius, rect, render_failed, repeat, restore,
    reverse_difference, rgba, right, rotate, rotate_at, round, rtl, sampling, saturation,
    save, save_layer, scale, screen, segments, size, soft_light, source, square, src,
    src_a_top, src_in, src_out, src_over, start_degrees, stroke, stroke_cap, stroke_join,
    stroke_miter, stroke_width, style, sweep_degrees, sweep_gradient, text, to,
    translate, union, unsupported_format, use_center, wbmp, webp, weight, width, winding,
    x, xor, y,
}
