// Generated by mix skia.codegen. Do not edit by hand.

fn draw_command(surface: &mut skia_safe::Surface, command: Term) -> NifResult<()> {
    let value = command.map_get(atoms::op())?.decode::<Atom>()?;
    match value {
        value if value == atoms::circle() => draw_circle(surface, command),
        value if value == atoms::clear() => draw_clear(surface, command),
        value if value == atoms::clip_circle() => clip_circle(surface, command),
        value if value == atoms::clip_path() => clip_path(surface, command),
        value if value == atoms::clip_rect() => clip_rect(surface, command),
        value if value == atoms::image() => draw_image(surface, command),
        value if value == atoms::line() => draw_line(surface, command),
        value if value == atoms::path() => draw_path(surface, command),
        value if value == atoms::rect() => draw_rect(surface, command),
        value if value == atoms::restore() => draw_restore(surface, command),
        value if value == atoms::rotate() => draw_rotate(surface, command),
        value if value == atoms::save() => draw_save(surface, command),
        value if value == atoms::save_layer() => draw_save_layer(surface, command),
        value if value == atoms::text() => draw_text(surface, command),
        value if value == atoms::translate() => draw_translate(surface, command),
        _ => Ok(()),
    }
}
