// Generated by mix skia.codegen. Do not edit by hand.

fn draw_save_impl(canvas: &Canvas) -> NifResult<()> {
    canvas.save();
    Ok(())
}
fn draw_restore_impl(canvas: &Canvas) -> NifResult<()> {
    canvas.restore();
    Ok(())
}
fn draw_save_layer_impl<'a>(
    canvas: &skia_safe::Canvas,
    opts: generated_opts::SaveLayerOpts<'a>,
    raw_opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    let bounds = match opts.bounds {
        Some(term) => Some(rect_from_term(term)?),
        None => None,
    };
    let mut paint = Paint::default();
    let alpha = (opts.opacity.unwrap_or(1.0).clamp(0.0, 1.0) * 255.0).round() as u8;
    paint.set_alpha(alpha);
    apply_blend_mode(&mut paint, raw_opts)?;
    match opts.blur {
        Some(sigma) => {
            match image_filters::blur((sigma, sigma), TileMode::Decal, None, None) {
                Some(filter) => {
                    paint.set_image_filter(filter);
                }
                None => {}
            };
        }
        None => {}
    };
    match opts.image_filter {
        Some(term) => {
            let filter = decode_image_filter(term)?;
            paint.set_image_filter(filter);
        }
        None => {}
    };
    let rec = SaveLayerRec::default().paint(&paint);
    let rec = match bounds.as_ref() {
        Some(bounds) => rec.bounds(bounds),
        None => rec,
    };
    canvas.save_layer(&rec);
    Ok(())
}
