// Generated by mix skia.codegen. Do not edit by hand.

fn draw_command(canvas: &skia_safe::Canvas, command: Term) -> NifResult<()> {
    let value = command.map_get(atoms::op())?.decode::<Atom>()?;
    match value {
        value if value == atoms::arc() => draw_arc(canvas, command),
        value if value == atoms::circle() => draw_circle(canvas, command),
        value if value == atoms::clear() => draw_clear(canvas, command),
        value if value == atoms::clip_circle() => clip_circle(canvas, command),
        value if value == atoms::clip_path() => clip_path(canvas, command),
        value if value == atoms::clip_rect() => clip_rect(canvas, command),
        value if value == atoms::concat() => draw_concat(canvas, command),
        value if value == atoms::image() => draw_image(canvas, command),
        value if value == atoms::line() => draw_line(canvas, command),
        value if value == atoms::oval() => draw_oval(canvas, command),
        value if value == atoms::path() => draw_path(canvas, command),
        value if value == atoms::path_op() => draw_path_op(canvas, command),
        value if value == atoms::path_outline() => draw_path_outline(canvas, command),
        value if value == atoms::picture() => draw_picture(canvas, command),
        value if value == atoms::rect() => draw_rect(canvas, command),
        value if value == atoms::restore() => draw_restore(canvas, command),
        value if value == atoms::rotate() => draw_rotate(canvas, command),
        value if value == atoms::rotate_at() => draw_rotate_at(canvas, command),
        value if value == atoms::save() => draw_save(canvas, command),
        value if value == atoms::save_layer() => draw_save_layer(canvas, command),
        value if value == atoms::scale() => draw_scale(canvas, command),
        value if value == atoms::text() => draw_text(canvas, command),
        value if value == atoms::translate() => draw_translate(canvas, command),
        _ => Err(rustler::Error::BadArg),
    }
}
