// Generated by mix skia.codegen. Do not edit by hand.

fn draw_text_impl<'a>(
    surface: &mut skia_safe::Surface,
    args: Vec<Term<'a>>,
    text_opts: generated_opts::TextOpts<'a>,
    _opts: &[(Atom, Term<'a>)],
) -> NifResult<()> {
    let text = args.first().ok_or(rustler::Error::BadArg)?.decode::<String>()?;
    let size = text_opts.size.unwrap_or(16.0);
    let mut font = match text_opts.font {
        Some(term) => font_from_term(term, size)?,
        None => Font::default(),
    };
    font.set_size(size);
    let paint = match text_opts.fill {
        Some(term) => fill_paint(decode_color(term)?),
        None => fill_paint(Color::BLACK),
    };
    if let Some(width) = text_opts.width {
        draw_paragraph_text(
            surface,
            &text,
            text_opts.x,
            text_opts.y,
            width,
            size,
            &paint,
            &text_opts,
        )?;
    } else {
        surface.canvas().draw_str(text, (text_opts.x, text_opts.y), &font, &paint);
    }
    Ok(())
}
fn draw_paragraph_text<'a>(
    surface: &mut skia_safe::Surface,
    text: &str,
    x: f32,
    y: f32,
    width: f32,
    size: f32,
    paint: &Paint,
    text_opts: &generated_opts::TextOpts<'a>,
) -> NifResult<()> {
    let mut text_style = TextStyle::new();
    text_style.set_font_size(size);
    text_style.set_color(paint.color());
    let mut paragraph_style = ParagraphStyle::new();
    paragraph_style.set_text_style(&text_style);
    if let Some(align) = text_opts.align {
        paragraph_style.set_text_align(decode_text_align(align)?);
    }
    if let Some(direction) = text_opts.direction {
        paragraph_style.set_text_direction(decode_text_direction(direction)?);
    }
    let mut font_collection = FontCollection::new();
    font_collection.set_default_font_manager(FontMgr::default(), None);
    let mut paragraph_builder = ParagraphBuilder::new(&paragraph_style, font_collection);
    paragraph_builder.push_style(&text_style);
    paragraph_builder.add_text(text);
    let mut paragraph = paragraph_builder.build();
    paragraph.layout(width);
    paragraph.paint(surface.canvas(), Point::new(x, y));
    Ok(())
}
fn decode_text_align(value: Atom) -> NifResult<TextAlign> {
    if value == atoms::center() {
        Ok(TextAlign::Center)
    } else if value == atoms::right() {
        Ok(TextAlign::Right)
    } else if value == atoms::justify() {
        Ok(TextAlign::Justify)
    } else if value == atoms::left() {
        Ok(TextAlign::Left)
    } else {
        Err(rustler::Error::BadArg)
    }
}
fn decode_text_direction(value: Atom) -> NifResult<TextDirection> {
    if value == atoms::rtl() {
        Ok(TextDirection::RTL)
    } else if value == atoms::ltr() {
        Ok(TextDirection::LTR)
    } else {
        Err(rustler::Error::BadArg)
    }
}
