name: Build precompiled NIFs

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    uses: elixir-vibe/actions/.github/workflows/elixir-rustler-release.yml@v1
    with:
      project-name: skia_native
      apt-packages: libfontconfig1-dev libfreetype6-dev
